name: Publish Crate

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GA_TOKEN }}
          fetch-depth: 0

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-workspaces
        run: cargo install cargo-workspaces

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "actions[bot]@github.com"

      - name: Bump version
        run: |
          cargo workspaces version ${{ github.event.inputs.version_bump }} --no-git-commit --yes

      - name: Commit version bump
        run: |
          git add .
          git commit -m "chore: bump crate version (${{ github.event.inputs.version_bump }})"
          git push

      - name: Configure cargo for publishing
        run: |
          mkdir -p ~/.cargo
          echo "[net]" >> ~/.cargo/config.toml
          echo "git-fetch-with-cli = true" >> ~/.cargo/config.toml

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          cargo publish --allow-dirty
